name: Container Image Scan

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  trivy-image:
    name: Trivy Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Build TaskFlow image
        run: docker build -t taskflow:${{ github.sha }} .

      - name: Scan container image
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          image-ref: taskflow:${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true
