name: SCA

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  trivy:
    name: Trivy Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true
<<<<<<< HEAD

=======
>>>>>>> main
